# Generated by Django 4.0.3 on 2022-03-04 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('address', models.TextField()),
                ('lat', models.FloatField()),
                ('long', models.FloatField()),
            ],
        ),
    ]
