# Generated by Django 4.0.3 on 2022-03-20 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0003_archive_archive_name_archive_archive_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='scale',
            field=models.IntegerField(blank=True, default=1),
        ),
    ]
