# Generated by Django 4.0.3 on 2022-03-20 19:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0005_remove_map_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='filename',
            field=models.FileField(default=django.utils.timezone.now, upload_to=''),
            preserve_default=False,
        ),
    ]
