# Generated by Django 4.0.3 on 2022-03-21 18:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('map_browser', '0007_remove_map_author1_id_remove_map_author2_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='authors',
            field=models.ManyToManyField(null=True, to='map_browser.people'),
        ),
        migrations.RemoveField(
            model_name='map',
            name='creator',
        ),
        migrations.AddField(
            model_name='map',
            name='creator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
