# Generated by Django 4.0.3 on 2022-03-21 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0008_alter_map_authors_remove_map_creator_map_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_team',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_unit',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
