# Generated by Django 4.0.3 on 2022-03-30 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0009_alter_archive_archive_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='filename',
            field=models.FileField(upload_to='maps'),
        ),
    ]
