# Generated by Django 4.0.3 on 2022-04-02 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0010_alter_map_filename'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='added_at',
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='map',
            name='source_text',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='created_at',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='map',
            name='creation_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='subject',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='map',
            name='subject_type',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
