# Generated by Django 4.0.3 on 2022-04-02 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'map_browser',
            '0011_map_added_at_map_source_text_alter_map_created_at_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='filename',
            field=models.ImageField(upload_to='maps'),
        ),
    ]
