# Generated by Django 4.0.3 on 2022-04-02 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0012_alter_map_filename'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='language_id',
        ),
        migrations.AddField(
            model_name='map',
            name='language_id',
            field=models.ManyToManyField(
                blank=True, null=True, to='map_browser.languages'
            ),
        ),
    ]
