# Generated by Django 4.0.3 on 2022-04-02 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0013_remove_map_language_id_map_language_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='scale',
            field=models.CharField(blank=True, default='1', max_length=200),
        ),
    ]
