# Generated by Django 4.0.3 on 2022-04-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0015_subjecttypes_remove_map_creation_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='creation_type',
        ),
        migrations.AddField(
            model_name='map',
            name='creation_type',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveField(
            model_name='map',
            name='subject_type',
        ),
        migrations.AddField(
            model_name='map',
            name='subject_type',
            field=models.ManyToManyField(blank=True, null=True, to='map_browser.subjecttypes'),
        ),
    ]
