# Generated by Django 4.0.3 on 2022-04-02 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0016_remove_map_creation_type_map_creation_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archive',
            name='archive_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_number',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_team',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_unit',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='languages',
            name='language_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='people',
            name='first_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='people',
            name='last_name',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AlterField(
            model_name='publicationplaces',
            name='city_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='publicationplaces',
            name='country_name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
