# Generated by Django 4.0.3 on 2022-04-02 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0017_alter_archive_archive_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publicationplaces',
            name='city_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='publicationplaces',
            name='country_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
