# Generated by Django 4.0.3 on 2022-04-03 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0018_alter_publicationplaces_city_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='created_at',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='map',
            name='publishing_address',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
