# Generated by Django 4.0.3 on 2022-04-03 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0020_alter_map_full_title_alter_map_short_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='creation_type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='keyword_geo',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='keyword_name',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='keyword_subject',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='scale',
            field=models.CharField(blank=True, default='1', max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='short_title',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='source_text',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='map',
            name='subject',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
