# Generated by Django 4.0.3 on 2022-04-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0021_alter_map_creation_type_alter_map_keyword_geo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='thumbnail',
            field=models.ImageField(default='_copy.jpg', upload_to='thumbnails'),
            preserve_default=False,
        ),
    ]
