# Generated by Django 4.0.3 on 2022-04-03 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0022_map_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='filename',
            field=models.ImageField(upload_to='maps/'),
        ),
        migrations.AlterField(
            model_name='map',
            name='thumbnail',
            field=models.ImageField(upload_to='thumbnails/'),
        ),
    ]
