# Generated by Django 4.0.3 on 2022-09-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0024_alter_map_archive_id_alter_map_corrector_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Dokument'),
        ),
        migrations.AddField(
            model_name='document',
            name='translation_file',
            field=models.FileField(blank=True, upload_to='', verbose_name='Tłumaczenie'),
        ),
    ]
