# Generated by Django 4.0.3 on 2022-09-15 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0025_document_doc_file_document_translation_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(
                blank=True, upload_to='documents/', verbose_name='Dokument'
            ),
        ),
        migrations.AlterField(
            model_name='document',
            name='translation_file',
            field=models.FileField(
                blank=True, upload_to='translations/', verbose_name='Tłumaczenie'
            ),
        ),
    ]
