# Generated by Django 4.0.3 on 2022-10-18 14:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0026_alter_document_doc_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='link',
            field=models.URLField(null=True, verbose_name='Link do dokumentu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='documents/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Podany format nie jest obsługiwany. Akceptowane są tylko pliki .pdf')], verbose_name='Dokument'),
        ),
        migrations.AlterField(
            model_name='document',
            name='link',
            field=models.URLField(null=True, verbose_name='Link do dokumentu'),
        ),
        migrations.AlterField(
            model_name='document',
            name='translation_file',
            field=models.FileField(blank=True, upload_to='translations/', validators=[django.core.validators.FileExtensionValidator(['pdf'], message='Podany format nie jest obsługiwany. Akceptowane są tylko pliki .pdf')], verbose_name='Tłumaczenie'),
        ),
        migrations.AlterField(
            model_name='document',
            name='volume',
            field=models.IntegerField(blank=True, null=True, verbose_name='Liczba/objętość'),
        ),
    ]
