# Generated by Django 4.0.3 on 2023-01-13 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0028_alter_document_link_alter_map_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='source_reference',
            field=models.ManyToManyField(blank=True, to='map_browser.document', verbose_name='Odwołanie do dokumentu źródłowego'),
        ),
        migrations.AlterField(
            model_name='map',
            name='link',
            field=models.URLField(blank=True, null=True, verbose_name='Link do Mapy'),
        ),
    ]
