# Generated by Django 4.0.3 on 2023-01-13 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0029_map_source_reference_alter_map_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='source_reference',
        ),
    ]
