# Generated by Django 4.0.3 on 2023-02-10 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map_browser', '0030_remove_map_source_reference'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='thumbnail',
            field=models.ImageField(null=True, upload_to='doc_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='document',
            name='archive_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=models.SET('N/A'), to='map_browser.archive', verbose_name='Archiwum'),
        ),
    ]
